//! Tool execution: finding and invoking function tools.
//!
//! This module contains the logic for matching tool names to function tools
//! in an agent's tool list, invoking them with the appropriate context, and
//! building tool output items.

use std::sync::Arc;

use serde_json::json;
use tokio::sync::RwLock;

use crate::agent::Agent;
use crate::context::RunContextWrapper;
use crate::items::{ItemHelpers, ResponseInputItem, RunItem, ToolCallOutputItem, ToolOutput};
use crate::lifecycle::RunHooks;
use crate::tool::{FunctionTool, Tool, ToolContext};

use super::turn_resolution::ParsedFunctionCall;

/// Find a function tool by name in the agent's tool list.
pub fn find_function_tool<'a, C: Send + Sync + 'static>(
    agent: &'a Agent<C>,
    tool_name: &str,
) -> Option<&'a FunctionTool<C>> {
    agent.tools.iter().find_map(|t| {
        if let Tool::Function(f) = t {
            if f.name == tool_name {
                return Some(f);
            }
        }
        None
    })
}

/// Result of executing all function tool calls for a single turn.
pub struct ToolExecutionResult {
    /// Additional run items generated by tool execution (tool call outputs).
    pub new_items: Vec<RunItem>,
    /// Response input items to append to the next turn's input.
    pub tool_outputs: Vec<ResponseInputItem>,
    /// Whether any tool calls were executed.
    pub had_tool_calls: bool,
    /// Names of tools that were called (used for `StopAtTools` behavior).
    pub stop_tool_names: Vec<String>,
}

/// Execute all function tool calls for a single turn.
///
/// Tool calls are executed sequentially in the order returned by the model,
/// preserving the guarantee that earlier tool calls complete (including any
/// shared-context side effects) before later ones begin. Each failed
/// invocation produces a `ToolOutput::Text("Error: ...")` output without
/// aborting the remaining calls.
pub async fn execute_tool_calls<C: Send + Sync + 'static>(
    agent: &Agent<C>,
    function_calls: &[ParsedFunctionCall],
    ctx: &Arc<RwLock<RunContextWrapper<C>>>,
    hooks: Option<&Arc<dyn RunHooks<C>>>,
) -> ToolExecutionResult {
    let mut new_items = Vec::new();
    let mut tool_outputs: Vec<ResponseInputItem> = Vec::new();
    let mut had_tool_calls = false;
    let mut stop_tool_names: Vec<String> = Vec::new();

    for fc in function_calls {
        had_tool_calls = true;
        let tool_name = &fc.name;
        let call_id = &fc.call_id;
        let arguments = &fc.arguments;

        // Fire tool start hooks.
        {
            let ctx_read = ctx.read().await;
            if let Some(hooks) = hooks {
                hooks.on_tool_start(&ctx_read, &agent.name, tool_name).await;
            }
            if let Some(agent_hooks) = &agent.hooks {
                agent_hooks.on_tool_start(&ctx_read, tool_name).await;
            }
        }

        // Find the matching function tool.
        let function_tool = find_function_tool(agent, tool_name);

        let output = if let Some(ft) = function_tool {
            let tool_ctx = ToolContext {
                context: Arc::clone(ctx),
                tool_name: tool_name.clone(),
                tool_call_id: call_id.clone(),
            };
            match ft.invoke(tool_ctx, arguments.clone()).await {
                Ok(out) => out,
                Err(e) => ToolOutput::Text(format!("Error: {e}")),
            }
        } else {
            ToolOutput::Text(format!("Error: tool '{tool_name}' not found"))
        };

        let output_text = match &output {
            ToolOutput::Text(s) => s.clone(),
            _ => String::from("<non-text output>"),
        };

        // Fire tool end hooks.
        {
            let ctx_read = ctx.read().await;
            if let Some(hooks) = hooks {
                hooks
                    .on_tool_end(&ctx_read, &agent.name, tool_name, &output_text)
                    .await;
            }
            if let Some(agent_hooks) = &agent.hooks {
                agent_hooks
                    .on_tool_end(&ctx_read, tool_name, &output_text)
                    .await;
            }
        }

        // Build the tool call output item.
        let output_item = ItemHelpers::tool_call_output_item(call_id, &output);
        tool_outputs.push(output_item.clone());

        new_items.push(RunItem::ToolCallOutput(ToolCallOutputItem {
            agent_name: agent.name.clone(),
            raw_item: output_item,
            output: serde_json::to_value(&output).unwrap_or(json!(null)),
        }));

        stop_tool_names.push(tool_name.clone());
    }

    ToolExecutionResult {
        new_items,
        tool_outputs,
        had_tool_calls,
        stop_tool_names,
    }
}
