[book]
authors = ["Bogdan Gewald"]
language = "en"
src = "src"
title = "OpenAI Agents SDK for Rust"

[build]
build-dir = "book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/UltraEmbeddedLab/openai-agent-sdk-rust"
edit-url-template = "https://github.com/UltraEmbeddedLab/openai-agent-sdk-rust/edit/main/docs/{path}"
